### ISSUE TITLE
Unable to use API endpoints multiple times.

### ISSUE THREAD

**Issue by thoka** [graydenshand/fluent_discourse#1]
While loading a lot of users via `admin.users.list.new.json.get({'page':n})` I failed to reuse the API endpoint `q = admin.users.list.new.json`. 

I'm wondering why all the submit methods (get, post, put, delete) execute `self._cache = []`, which prohibits reuse of an endpoint.

**Comment by graydenshand** [comment]
Hey @thoka thanks for raising the issue. I just got back online after a vacation and injury, I'll try to take a closer look at this this week.

In general, I agree endpoints should be able to be reused in subsequent requests, so it does sound like a bug.

**Comment by graydenshand** [comment]
@thoka fix for this has been released: https://pypi.org/project/fluent-discourse/1.0.1/

Thanks again for surfacing!
